image: "registry.gitlab.com/interlay/btc-parachain:ci"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build

test-crates:
  stage: test
  before_script:
    - rustc --version
    - rustfmt --version
    - cargo --version
  script:
    - git submodule update --init vendor/relayer-core
    # - cargo fmt -- --check
    - cargo check --all
    - cargo test --all 
  cache:
    key: cargo
    paths:
      - .cargo

docker-publish-staked-relayer:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - apk add git
    - git submodule update --init vendor/relayer-core
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:staked-relayer-latest || true
    - |
      docker build --cache-from $CI_REGISTRY_IMAGE:staked-relayer-latest \
      --tag $CI_REGISTRY_IMAGE:staked-relayer-$CI_COMMIT_SHA \
      --tag $CI_REGISTRY_IMAGE:staked-relayer-latest \
      --file staked-relayer/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:staked-relayer-$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:staked-relayer-latest