image: "registry.gitlab.com/interlay/btc-parachain:ci"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

stages:
  - test
  - build

test-crates:
  stage: test
  before_script:
    - rustc --version
    - rustfmt --version
    - cargo --version
  script:
    - git submodule update --init vendor/relayer-core
    # - cargo fmt -- --check
    - cargo check --all
    - cargo test --all 
  cache:
    key: cargo
    paths:
      - .cargo

docker-publish-staked-relayer:
  stage: build
  image: docker:19.03.8
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.8-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build . -f staked-relayer/Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA