[workspace]
members = [
  "oracle",
  "staked-relayer",
  "runtime",
  "testdata-gen",
  "vault",
  "bitcoin",
  "backend"
]

[patch.crates-io]
jsonrpsee = { git = "https://github.com/interlay/jsonrpsee", rev = "95d98e18a5459ae82477a14f426243621a927f0f" }