[workspace]
members = [
  "oracle",
  "staked-relayer",
  "runtime",
  "testdata-gen",
  "vault",
  "bitcoin",
  "faucet"
]

[patch.crates-io]
jsonrpsee = { git = "https://github.com/interlay/jsonrpsee", rev = "3e24bf06df258d94fbd7215b35536af2d5d68b0b" }