[workspace]
members = [
  "oracle",
  "staked-relayer",
  "runtime",
  "testdata-gen",
  "vault",
  "bitcoin",
  "backend"
]
[patch.crates-io]
jsonrpsee = { git = 'https://github.com/gregdhill/jsonrpsee', branch = '0.1.0', version = '0.1.0', features = ["ws"] }