version: "3.8"
services:
  polkabtc:
    image: "registry.gitlab.com/interlay/btc-parachain:dev"
    command:
      - btc-parachain
      - --dev
    network_mode: host
    ports:
      - "9944:9944"
  bitcoind:
    image: "ruimarinho/bitcoin-core:0.20"
    command:
      - -regtest
      - -rpcuser=rpcuser
      - -rpcpassword=rpcpassword
    network_mode: host
    ports:
      - "18443:18443"
