[package]
name = "runtime"
version = "1.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[features]
default = []
testing-utils = [
    # "substrate-subxt/client",
    # "substrate-subxt-client",
    "tempdir",
    "interbtc",
    "rand",
]

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive", "full"] }
async-trait = "0.1.40"
thiserror = "1.0"
serde_json = "1.0.57"
tokio = { version = "1.0", features = ["full"] }
backoff = { version = "0.3.0", features = ["tokio"] }
futures = "0.3.5"
clap = "3.0.0-beta.2"
log = "0.4.0"
url = "2"

# Substrate dependencies
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.11" }

# Subxt dependencies
subxt = { package = "subxt", git = "https://github.com/interlay/substrate-subxt", rev = "3af8331231f1dd3c328c1e96a6b48a10dc1b3ffb" }
subxt-client = { package = "subxt-client", git = "https://github.com/interlay/substrate-subxt", rev = "3af8331231f1dd3c328c1e96a6b48a10dc1b3ffb" }

jsonrpsee-types = "0.3.0"
jsonrpsee-ws-client = "0.3.0"

# Polkadot dependencies
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.11" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.11" }

bitcoin = { path = "../bitcoin"}

# Dependencies for the testing utils for integration tests
tempdir = {version = "0.3.7", optional = true }
interbtc = { package = "interbtc-standalone", git = "https://github.com/interlay/interbtc", rev = "0ce5f7bab9e7b5b15a35c1df7282bb983055deb4", optional = true }
rand = { version = "0.7", optional = true }

[dependencies.primitives]
git = "https://github.com/interlay/interbtc"
rev = "0ce5f7bab9e7b5b15a35c1df7282bb983055deb4"
package = "interbtc-primitives"

[dependencies.module-bitcoin]
git = "https://github.com/interlay/interbtc"
rev = "0ce5f7bab9e7b5b15a35c1df7282bb983055deb4"
package = "bitcoin"

[dependencies.module-btc-relay]
git = "https://github.com/interlay/interbtc"
rev = "0ce5f7bab9e7b5b15a35c1df7282bb983055deb4"
package = "btc-relay"

[dependencies.module-security]
git = "https://github.com/interlay/interbtc"
rev = "0ce5f7bab9e7b5b15a35c1df7282bb983055deb4"
package = "security"

[dependencies.module-vault-registry]
git = "https://github.com/interlay/interbtc"
rev = "0ce5f7bab9e7b5b15a35c1df7282bb983055deb4"
package = "vault-registry"

[dependencies.module-oracle-rpc-runtime-api]
git = "https://github.com/interlay/interbtc"
rev = "0ce5f7bab9e7b5b15a35c1df7282bb983055deb4"
package = "module-oracle-rpc-runtime-api"



[dev-dependencies]
runtime = { path = ".", features = ["testing-utils"] }
tempdir = "0.3.7"
env_logger = "0.8.3"