[package]
name = "runtime"
version = "0.7.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[features]
default = []
testing-utils = [
    "substrate-subxt/client",
    "substrate-subxt-client",
    "tempdir",
    "btc-parachain",
    "btc-parachain-service",
    "bitcoin",
    "rand",
]

[dependencies]
serde = { version = "1.0.119", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive", "full"] }
async-trait = "0.1.40"
thiserror = "1.0"
serde_json = "1.0.57"
tokio = { version = "0.2.22", features = ["full"] }
backoff = { version = "0.2.1", features = ["tokio"] }
futures = "0.3.5"
clap = "3.0.0-beta.2"
log = "0.4.0"
url = "2"

# Substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }

# Subxt dependencies
substrate-subxt-proc-macro = { git = "https://github.com/interlay/substrate-subxt", rev = "ceef243f8700fb2f4ded9461a9d725af1a333aac" }
substrate-subxt = { git = "https://github.com/interlay/substrate-subxt", rev = "ceef243f8700fb2f4ded9461a9d725af1a333aac" }

jsonrpsee-types = "=0.2.0-alpha.6"
jsonrpsee-ws-client = "=0.2.0-alpha.6"

# Polkadot dependencies
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.1" }
parachain = { package = "polkadot-parachain", git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.1" }

# Dependencies for the testing utils for integration tests
substrate-subxt-client = { git = "https://github.com/interlay/substrate-subxt", rev = "ceef243f8700fb2f4ded9461a9d725af1a333aac", optional = true }
tempdir = {version = "0.3.7", optional = true }
btc-parachain = { git = "ssh://git@github.com/interlay/interbtc.git", branch = "master", features = ["aura-grandpa"], optional = true }
btc-parachain-service = { git = "ssh://git@github.com/interlay/interbtc.git", branch = "master", features = ["aura-grandpa"], optional = true }
bitcoin = { path = "../bitcoin", optional = true }
rand = { version = "0.7", optional = true }

[dependencies.module-bitcoin]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "bitcoin"

[dependencies.module-refund]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "refund"

[dependencies.module-btc-relay]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "btc-relay"

[dependencies.module-security]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "security"

[dependencies.module-staked-relayers]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "staked-relayers"

[dependencies.module-vault-registry]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "vault-registry"

[dependencies.module-exchange-rate-oracle-rpc-runtime-api]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "module-exchange-rate-oracle-rpc-runtime-api"

[dependencies.module-issue]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "issue"

[dependencies.module-redeem]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "redeem"

[dependencies.module-replace]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "replace"

[dependencies.module-exchange-rate-oracle]
git = "ssh://git@github.com/interlay/interbtc.git"
branch = "master"
package = "exchange-rate-oracle"

[dev-dependencies]
substrate-subxt-client = { git = "https://github.com/interlay/substrate-subxt", rev = "ceef243f8700fb2f4ded9461a9d725af1a333aac" }
btc-parachain = { git = "ssh://git@github.com/interlay/interbtc.git", branch = "master", features = ["aura-grandpa"] }
btc-parachain-service = { git = "ssh://git@github.com/interlay/interbtc.git", branch = "master", features = ["aura-grandpa"] }
tempdir = "0.3.7"
env_logger = "0.8.3"