[package]
name = "runtime"
version = "0.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = "1.3.1"
frame-support = "2.0.0"
async-trait = "0.1.40"
sp-runtime = "2.0.0"
sp-core = "2.0.0"
thiserror = "1.0"
serde_json = "1.0.57"
tokio = { version = "0.2.22", features = ["full"] }
jsonrpsee = "0.1.0"

substrate-subxt-proc-macro = { git = "https://github.com/paritytech/substrate-subxt", branch = "master" }
substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt", branch = "master" }

[dependencies.module-bitcoin]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.1.1"
package = "bitcoin"
# path = "../../btc-parachain/crates/bitcoin"

[dependencies.module-security]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "2.0.0"
package = "security"
# path = "../../btc-parachain/crates/security"

[dependencies.module-staked-relayers]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "2.0.0"
package = "staked-relayers"
# path = "../../btc-parachain/crates/staked-relayers"

[dependencies.module-vault-registry]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "2.0.0"
package = "vault-registry"
# path = "../../btc-parachain/crates/vault-registry"

[dev-dependencies]
substrate-subxt-client = "0.4.0"
tempdir = "0.3.7"
sp-keyring = "2.0.0"

[dev-dependencies.btc-parachain]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
