[package]
name = "runtime"
version = "0.3.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = "1.3.6"
async-trait = "0.1.40"
thiserror = "1.0"
serde_json = "1.0.57"
serde = "1.0.116"
tokio = { version = "0.2.22", features = ["full"] }
jsonrpsee = "0.1.0"
futures = "0.3.5"
clap = "3.0.0-beta.2"

# Substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# Subxt dependencies
substrate-subxt-proc-macro = { git = "https://github.com/interlay/substrate-subxt", rev = "c7168df" }
substrate-subxt = { git = "https://github.com/interlay/substrate-subxt", rev = "c7168df" }

[dependencies.module-bitcoin]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "bitcoin"

[dependencies.module-refund]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "refund"

[dependencies.module-btc-relay]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "btc-relay"

[dependencies.module-security]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "security"

[dependencies.module-staked-relayers]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "staked-relayers"

[dependencies.module-vault-registry]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "vault-registry"

[dependencies.module-exchange-rate-oracle-rpc-runtime-api]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "module-exchange-rate-oracle-rpc-runtime-api"

[dependencies.module-issue]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "issue"

[dependencies.module-redeem]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "redeem"

[dependencies.module-replace]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "replace"

[dependencies.module-exchange-rate-oracle]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.5.0"
package = "exchange-rate-oracle"

[dev-dependencies]
substrate-subxt-client = { git = "https://github.com/interlay/substrate-subxt", rev = "c7168df" }
tempdir = "0.3.7"
btc-parachain = { git = "https://gitlab.com/interlay/btc-parachain", branch = "dev", version = "0.5.0", features = ["aura-grandpa"] }
btc-parachain-service = { git = "https://gitlab.com/interlay/btc-parachain", branch = "dev", version = "0.5.0", features = ["aura-grandpa"] }
