[package]
name = "runtime"
version = "0.7.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[features]
default = []
testing-utils = [
    "substrate-subxt/client",
    "substrate-subxt-client",
    "tempdir",
    "interbtc",
    "bitcoin",
    "rand",
]

[dependencies]
serde = { version = "1.0.119", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive", "full"] }
async-trait = "0.1.40"
thiserror = "1.0"
serde_json = "1.0.57"
tokio = { version = "1.0", features = ["full"] }
backoff = { version = "0.3.0", features = ["tokio"] }
futures = "0.3.5"
clap = "3.0.0-beta.2"
log = "0.4.0"
url = "2"

# Substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

# Subxt dependencies
substrate-subxt-proc-macro = { git = "https://github.com/interlay/substrate-subxt", rev = "8bfaa511d34169b55888c5ad4288c8bafd203f24" }
substrate-subxt = { git = "https://github.com/interlay/substrate-subxt", rev = "8bfaa511d34169b55888c5ad4288c8bafd203f24" }

jsonrpsee-types = "0.3.0"
jsonrpsee-ws-client = "0.3.0"

# Polkadot dependencies
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.7" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.7" }

# Dependencies for the testing utils for integration tests
substrate-subxt-client = { git = "https://github.com/interlay/substrate-subxt", rev = "8bfaa511d34169b55888c5ad4288c8bafd203f24", optional = true }
tempdir = {version = "0.3.7", optional = true }
interbtc = { package = "interbtc-standalone", git = "https://github.com/interlay/interbtc", rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb", optional = true }
bitcoin = { path = "../bitcoin", optional = true }
rand = { version = "0.7", optional = true }

[dependencies.module-bitcoin]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "bitcoin"

[dependencies.module-refund]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "refund"

[dependencies.module-btc-relay]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "btc-relay"

[dependencies.module-security]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "security"

[dependencies.module-relay]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "relay"

[dependencies.module-vault-registry]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "vault-registry"

[dependencies.module-exchange-rate-oracle-rpc-runtime-api]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "module-exchange-rate-oracle-rpc-runtime-api"

[dependencies.module-issue]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "issue"

[dependencies.module-redeem]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "redeem"

[dependencies.module-replace]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "replace"

[dependencies.module-exchange-rate-oracle]
git = "https://github.com/interlay/interbtc"
rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb"
package = "exchange-rate-oracle"

[dev-dependencies]
substrate-subxt-client = { git = "https://github.com/interlay/substrate-subxt", rev = "8bfaa511d34169b55888c5ad4288c8bafd203f24" }
interbtc = { package = "interbtc-standalone", git = "https://github.com/interlay/interbtc", rev = "39565ae0a5402a00dc1f222ea322a13303cab9fb" }
tempdir = "0.3.7"
env_logger = "0.8.3"