[package]
name = "runtime"
version = "0.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
substrate-subxt = { path = "../../substrate-subxt" }
parity-scale-codec = "1.3.1"
frame-system = "2.0.0-rc6"
frame-support = "2.0.0-rc6"
substrate-subxt-proc-macro = "0.12.0"

sp-keyring = { version = "2.0.0-rc6", package = "sp-keyring" }
sp-runtime = { version = "2.0.0-rc6", package = "sp-runtime" }
sp-timestamp = { version = "2.0.0-rc6", package = "sp-timestamp" }
sp-core = { version = "2.0.0-rc6", package = "sp-core" }
pallet-indices = { version = "2.0.0-rc6", package = "pallet-indices" }
pallet-balances = { version = "2.0.0-rc6", package = "pallet-balances" }

[dependencies.module-bitcoin]
# git = "https://gitlab.com/interlay/btc-parachain"
version = "0.1.1"
package = "bitcoin"
# branch = "dev"
path = "../../btc-parachain/crates/bitcoin"

[dependencies.module-security]
# git = "https://gitlab.com/interlay/btc-parachain"
version = "2.0.0-rc6"
package = "security"
# branch = "dev"
path = "../../btc-parachain/crates/security"

[dependencies.module-staked-relayers]
# git = "https://gitlab.com/interlay/btc-parachain"
version = "2.0.0-rc6"
package = "staked-relayers"
# branch = "dev"
path = "../../btc-parachain/crates/staked-relayers"

[dependencies.module-vault-registry]
# git = "https://gitlab.com/interlay/btc-parachain"
version = "2.0.0-rc6"
package = "vault-registry"
# branch = "dev"
path = "../../btc-parachain/crates/vault-registry"
