[package]
name = "testdata-gen"
version = "0.1.0"
authors = ["Interlay <dev@interlay.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
parity-scale-codec = "1.3.1"
frame-system = "2.0.0"
sp-keyring = "2.0.0"
sp-core = "2.0.0"
primitive-types = { default-features = false, version = "0.7.2", features = ["codec"]}
hex = "0.4.2"
substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt", branch = "master" }
substrate-subxt-proc-macro = "0.12.0"
runtime = { path = "../runtime" }
relayer-core = { git = "https://gitlab.com/interlay/relayer-core", branch = "main" }

[dependencies.module-bitcoin]
git = "https://gitlab.com/interlay/btc-parachain"
branch = "dev"
version = "0.1.1"
package = "bitcoin"