[package]
name = "staked-relayer"
version = "0.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.7.1"
parity-scale-codec = "1.3.1"
frame-system = "2.0.0-rc6"
substrate-subxt-proc-macro = "0.12.0"
tokio = { version = "0.2.22", features = ["full"] }
hex = "0.4.2"
thiserror = "1.0"
futures = "0.3.5"
tonic = "0.3"
prost = "0.6"
serde_json = "1.0.57"
clap = "3.0.0-beta.1"
sp-keyring = "2.0.0-rc6"
sp-core = "2.0.0-rc6"
async-trait = "0.1.40"

# TODO: https://github.com/paritytech/substrate-subxt/pull/158
substrate-subxt = { path = "../../substrate-subxt" }
runtime = { path = "../runtime" }
relayer-core = { path = "../../relayer-core" }

[build-dependencies]
tonic-build = "0.3"

[dev-dependencies]
tokio-test = "0.2.1"
mockall = "0.8.1"
substrate-subxt-client = "0.4.0"
tempdir = "0.3.7"

[dev-dependencies.btc-parachain]
path = "../../btc-parachain/parachain"

[dev-dependencies.exchange-rate-oracle]
path = "../../btc-parachain/crates/exchange-rate-oracle"

[dev-dependencies.btc-relay]
path = "../../btc-parachain/crates/btc-relay"

[dev-dependencies.vault-registry]
path = "../../btc-parachain/crates/vault-registry"
