[package]
name = "staked-relayer"
version = "0.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.7.1"
parity-scale-codec = "1.3.1"
frame-system = "2.0.0"
tokio = { version = "0.2.22", features = ["full"] }
hex = "0.4.2"
thiserror = "1.0"
futures = "0.3.5"
clap = "3.0.0-beta.1"
sp-keyring = "2.0.0"
sp-core = "2.0.0"
async-trait = "0.1.40"
serde = "1.0.116"
relayer-core = { git = "https://gitlab.com/interlay/relayer-core", branch = "master" }
runtime = { path = "../runtime" }
bitcoin = { path = "../bitcoin" }
jsonrpc-http-server = "15.1.0"

[dev-dependencies]
mockall = "0.8.1"
