[package]
name = "staked-relayer"
version = "0.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
substrate-subxt = "0.12.0"
log = "0.4.0"
env_logger = "0.7.1"
parity-scale-codec = "1.3.1"
frame-system = "2.0.0-rc6"
substrate-subxt-proc-macro = "0.12.0"
tokio = { version = "0.2", features = ["full"] }
warp = "0.2"
hex = "0.4.2"

sp-keyring = { version = "2.0.0-rc6", package = "sp-keyring" }
sp-runtime = { version = "2.0.0-rc6", package = "sp-runtime" }
sp-core = { version = "2.0.0-rc6", package = "sp-core" }
pallet-indices = { version = "2.0.0-rc6", package = "pallet-indices" }
pallet-balances = { version = "2.0.0-rc6", package = "pallet-balances" }

[dependencies.module-bitcoin]
git = "https://gitlab.com/interlay/btc-parachain"
version = "0.1.1"
package = "bitcoin"
branch = "dev"

[dependencies.module-security]
git = "https://gitlab.com/interlay/btc-parachain"
version = "2.0.0-rc6"
package = "security"
branch = "dev"

[dependencies.module-staked-relayers]
git = "https://gitlab.com/interlay/btc-parachain"
version = "2.0.0-rc6"
package = "staked-relayers"
branch = "dev"