[package]
name = "staked-relayer"
version = "0.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.7.1"
parity-scale-codec = "1.3.1"
frame-system = "2.0.0-rc6"
substrate-subxt-proc-macro = "0.12.0"
tokio = { version = "0.2.22", features = ["full"] }
hex = "0.4.2"
thiserror = "1.0"
futures = "0.3.5"
tonic = "0.3"
prost = "0.6"
bitcoin = "0.23.0"
serde_json = "1.0.57"
clap = "3.0.0-beta.1"
sp-keyring = { version = "2.0.0-rc6", package = "sp-keyring" }
sp-core = { version = "2.0.0-rc6", package = "sp-core" }

# TODO: https://github.com/paritytech/substrate-subxt/pull/158
substrate-subxt = { path = "../../substrate-subxt" }
runtime = { path = "../runtime" }
relayer-core = { path = "../../relayer-core" }

[build-dependencies]
tonic-build = "0.3"

[dev-dependencies]
tokio-test = "0.2.1"
mockall = "0.8.1"