[package]
name = "staked-relayer"
version = "0.1.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.7.1"
parity-scale-codec = "1.3.1"
frame-system = "2.0.0-rc6"
substrate-subxt-proc-macro = "0.12.0"
tokio = { version = "0.2.22", features = ["full"] }
hex = "0.4.2"
thiserror = "1.0"
futures = "0.3.5"
clap = "3.0.0-beta.1"
sp-keyring = "2.0.0-rc6"
sp-core = "2.0.0-rc6"
async-trait = "0.1.40"
warp = "0.2"

substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt", branch = "master" }
runtime = { path = "../runtime" }
relayer-core = { path = "../vendor/relayer-core" }

[dev-dependencies]
tokio-test = "0.2.1"
mockall = "0.8.1"
