[package]
name = "oracle"
version = "0.2.2"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.7.1"
clap = "3.0.0-beta.2"
tokio = { version = "0.2.22", features = ["full"] }
runtime = { path = "../runtime" }
chrono = "0.4"
thiserror = "1.0"
reqwest = { version = "0.10.9", features = ["json"] }

# Substrate dependencies
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }