[package]
name = "service"
version = "0.6.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
async-trait = "0.1.40"
log = "0.4.0"
futures = "0.3.5"
clap = "3.0.0-beta.2"
tokio = { version = "0.2.22", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Workspace dependencies
bitcoin = { path = "../bitcoin", features = ["cli"] }
runtime = { path = "../runtime" }
