[package]
name = "faucet"
version = "0.2.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.7.1"
clap = "3.0.0-beta.2"
tokio = { version = "0.2.22", features = ["full"] }
runtime = { path = "../runtime" }
bitcoin = { path = "../bitcoin", features = ["cli"] }
thiserror = "1.0"
jsonrpc-http-server = "15.1.0"
parity-scale-codec = "1.3.1"
serde = "1.0.116"
futures = "0.3.5"
hex = "0.4.2"
