[package]
name = "bitcoin"
version = "0.2.0"
authors = ["Interlay <contact@interlay.io>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
bitcoincore-rpc = { git = "https://github.com/gregdhill/rust-bitcoincore-rpc" }
hex = "0.4.2"
sp-core = "2.0.0-rc6"
async-trait = "0.1.40"
tokio = { version = "0.2.22", features = ["full"] }
backoff = { version = "0.2.1", features = ["tokio"] }
clap = { version = "3.0.0-beta.2", optional = true }
rand = "0.7.3"
num = "0.2"
num-traits = "0.2"
num-derive = "0.3"

[dev-dependencies]
mockall = "0.8.1"

[features]
regtest = []
cli = ["clap"]
