[package]
name = "procedural"
version = '1.0.0'
authors = ["Interlay Ltd"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
quote = "1.0.3"
syn = { version = "1.0.7", features = ["full"] }

[features]
default = ["std"]
std = []
